In [2]:
import numpy as np 
import pandas as pd
from xgboost import XGBClassifier
import matplotlib.pyplot as plt
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.metrics import roc_auc_score, f1_score, confusion_matrix, ConfusionMatrixDisplay
from imblearn.pipeline import Pipeline as ImbPipeline
from imblearn.over_sampling import SMOTE
from catboost import CatBoostClassifier
import shap

/home/sunsun/miniconda3/envs/prescriptive_datascience/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
corn_df = pd.read_csv('data/CornCostReturn.csv')
corn_df.head()

,Commodity,Category,Item,Units,Size,Region,Country,Year,Value,Survey base year
0,Corn,Gross value of production,"Primary product, grain",dollars per planted acre,No specific size,Eastern Uplands,United States,2025,757.13,Base survey of 2021
1,Corn,Supporting information,Price,dollars per bushel at harvest,No specific size,Prairie Gateway,United States,2025,4.00,Base survey of 2021
2,Corn,Operating costs,Interest on operating capital,dollars per planted acre,No specific size,Southern Seaboard,United States,2025,10.05,Base survey of 2021
3,Corn,Operating costs,"Total, operating costs",dollars per planted acre,No specific size,Eastern Uplands,United States,2025,476.28,Base survey of 2021
4,Corn,Supporting information,Price,dollars per bushel at harvest,No specific size,Northern Great Plains,United States,2025,3.71,Base survey of 2021

In [4]:
cotton_df = pd.read_csv('data/CottonCostReturn.csv')
cotton_df.head()

,Commodity,Category,Item,Units,Size,Region,Country,Year,Value,Survey base year
0,Cotton,Net value,Value of production less operating costs,dollars per planted acre,No specific size,Prairie Gateway,United States,2025,131.34,Base survey of 2019
1,Cotton,Net value,Value of production less operating costs,dollars per planted acre,No specific size,Mississippi Portal,United States,2025,145.03,Base survey of 2019
2,Cotton,Net value,Value of production less total costs listed,dollars per planted acre,No specific size,Fruitful Rim,United States,2025,103.12,Base survey of 2019
3,Cotton,Allocated overhead,Taxes and insurance,dollars per planted acre,No specific size,Prairie Gateway,United States,2025,4.95,Base survey of 2019
4,Cotton,Allocated overhead,Hired labor,dollars per planted acre,No specific size,Prairie Gateway,United States,2025,24.07,Base survey of 2019

In [6]:
soybean_df = pd.read_csv('data/SoybeanCostReturn.csv')
soybean_df.head()

,Commodity,Category,Item,Units,Size,Region,Country,Year,Value,Survey base year
0,Soybean,Allocated overhead,Hired labor,dollars per planted acre,No specific size,Prairie Gateway,United States,2025,13.80,Base survey of 2023
1,Soybean,Allocated overhead,Taxes and insurance,dollars per planted acre,No specific size,Prairie Gateway,United States,2025,14.24,Base survey of 2023
2,Soybean,Operating costs,Purchased irrigation water,dollars per planted acre,No specific size,Southern Seaboard,United States,2025,0.18,Base survey of 2023
3,Soybean,Supporting information,Enterprise size,planted acres,No specific size,Eastern Uplands,United States,2025,375.00,Base survey of 2023
4,Soybean,Allocated overhead,Hired labor,dollars per planted acre,No specific size,Mississippi Portal,United States,2025,18.57,Base survey of 2023

In [7]:
wheat_df = pd.read_csv('data/WheatCostReturn.csv')
wheat_df.head(15)

,Commodity,Category,Item,Units,Size,Region,Country,Year,Value,Survey base year
0,Wheat,Operating costs,"Total, operating costs",dollars per planted acre,No specific size,Heartland,United States,2025,230.85,Base survey of 2022
1,Wheat,Allocated overhead,General farm overhead,dollars per planted acre,No specific size,Heartland,United States,2025,7.70,Base survey of 2022
2,Wheat,Operating costs,Fertilizer,dollars per planted acre,No specific size,Heartland,United States,2025,103.70,Base survey of 2022
3,Wheat,Operating costs,Seed,dollars per planted acre,No specific size,Northern Crescent,United States,2025,30.21,Base survey of 2022
4,Wheat,Operating costs,Other variable expenses,dollars per planted acre,No specific size,Prairie Gateway,United States,2025,0.34,Base survey of 2022
5,Wheat,Operating costs,"Total, operating costs",dollars per planted acre,No specific size,Basin and Range,United States,2025,201.28,Base survey of 2022
6,Wheat,Operating costs,Interest on operating inputs,dollars per planted acre,No specific size,Prairie Gateway,United States,2025,2.85,Base survey of 2022
7,Wheat,Gross value of production,"Total, gross value of production",dollars per planted acre,No specific size,U.S. total,United States,2025,280.32,Base survey of 2022
8,Wheat,Allocated overhead,Taxes and insurance,dollars per planted acre,No specific size,U.S. total,United States,2025,8.26,Base survey of 2022
9,Wheat,Gross value of production,"Primary product, grain",dollars per planted acre,No specific size,Northern Great Plains,United States,2025,231.55,Base survey of 2022
10,Wheat,Operating costs,Interest on operating inputs,dollars per planted acre,No specific size,U.S. total,United States,2025,3.16,Base survey of 2022
11,Wheat,Operating costs,Seed,dollars per planted acre,No specific size,Northern Great Plains,United States,2025,15.30,Base survey of 2022
12,Wheat,Operating costs,"Total, operating costs",dollars per planted acre,No specific size,U.S. total,United States,2025,162.96,Base survey of 2022
13,Wheat,Gross value of production,"Total, gross value of production",dollars per planted acre,No specific size,Basin and Range,United States,2025,374.86,Base survey of 2022
14,Wheat,Gross value of production,"Primary product, grain",dollars per planted acre,No specific size,Fruitful Rim,United States,2025,322.42,Base survey of 2022

In [8]:
crop_forecast_df = pd.read_csv('data/cop_forecast.csv')
crop_forecast_df.head(10)

,Commodity,Category,Item,Units,Region,Year,Value
0,Corn,Operating costs,Seed,Dollars per planted acre,U.S. total,2026F,111.06
1,Corn,Operating costs,Fertilizer,Dollars per planted acre,U.S. total,2026F,184.33
2,Corn,Operating costs,Chemicals,Dollars per planted acre,U.S. total,2026F,46.44
3,Corn,Operating costs,Custom operations,Dollars per planted acre,U.S. total,2026F,38.56
4,Corn,Operating costs,"Fuel, lube, and electricity",Dollars per planted acre,U.S. total,2026F,34.19
5,Corn,Operating costs,Repairs,Dollars per planted acre,U.S. total,2026F,50.40
6,Corn,Operating costs,Other variable expenses,Dollars per planted acre,U.S. total,2026F,0.30
7,Corn,Operating costs,Interest on operating capital,Dollars per planted acre,U.S. total,2026F,7.75
8,Corn,Operating costs,"Total, operating costs",Dollars per planted acre,U.S. total,2026F,473.03
9,Corn,Allocated overhead,Hired labor,Dollars per planted acre,U.S. total,2026F,4.78

In [9]:
for df in (corn_df, cotton_df, soybean_df, wheat_df, crop_forecast_df):
    df.info()
    print('\n')

<class 'pandas.DataFrame'>
RangeIndex: 5665 entries, 0 to 5664
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Commodity         5665 non-null   str
 1   Category          5665 non-null   str
 2   Item              5665 non-null   str
 3   Units             5665 non-null   str
 4   Size              5665 non-null   str
 5   Region            5665 non-null   str
 6   Country           5665 non-null   str
 7   Year              5665 non-null   int64
 8   Value             5665 non-null   float64
 9   Survey base year  5665 non-null   str
dtypes: float64(1), int64(1), str(8)
memory usage: 442.7 KB


<class 'pandas.DataFrame'>
RangeIndex: 5550 entries, 0 to 5549
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Commodity         5550 non-null   str
 1   Category          5550 non-null   str
 2   Item              5550 non-null   str
 3   Units             5550 non-null   str
 4   Size              5550 non-null   str
 5   Region            5550 non-null   str
 6   Country           5550 non-null   str
 7   Year              5550 non-null   int64
 8   Value             5550 non-null   float64
 9   Survey base year  5550 non-null   str
dtypes: float64(1), int64(1), str(8)
memory usage: 433.7 KB


<class 'pandas.DataFrame'>
RangeIndex: 6026 entries, 0 to 6025
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Commodity         6026 non-null   str
 1   Category          6026 non-null   str
 2   Item              6026 non-null   str
 3   Units             6026 non-null   str
 4   Size              6026 non-null   str
 5   Region            6026 non-null   str
 6   Country           6026 non-null   str
 7   Year              6026 non-null   int64
 8   Value             6026 non-null   float64
 9   Survey base year  6026 non-null   str
dtypes: float64(1), int64(1), str(8)
memory usage: 470.9 KB


<class 'pandas.DataFrame'>
RangeIndex: 6204 entries, 0 to 6203
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Commodity         6204 non-null   str
 1   Category          6204 non-null   str
 2   Item              6204 non-null   str
 3   Units             6204 non-null   str
 4   Size              6204 non-null   str
 5   Region            6204 non-null   str
 6   Country           6204 non-null   str
 7   Year              6204 non-null   int64
 8   Value             6204 non-null   float64
 9   Survey base year  6204 non-null   str
dtypes: float64(1), int64(1), str(8)
memory usage: 484.8 KB


<class 'pandas.DataFrame'>
RangeIndex: 306 entries, 0 to 305
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Commodity  306 non-null    str
 1   Category   306 non-null    str
 2   Item       306 non-null    str
 3   Units      306 non-null    str
 4   Region     306 non-null    str
 5   Year       306 non-null    str
 6   Value      306 non-null    float64
dtypes: float64(1), str(6)
memory usage: 16.9 KB

In [10]:
for df in (corn_df, cotton_df, soybean_df, wheat_df, crop_forecast_df):
    str_cols = df.select_dtypes(include=['object', 'string'])
    for col in str_cols:
        print(f'\n', str_cols[col].value_counts())
    print('----------------------------\n')

 Commodity
Corn    5665
Name: count, dtype: int64

 Category
Operating costs              1890
Allocated overhead           1470
Gross value of production     630
Supporting information        630
Net value                     420
Production practices          415
Costs listed                  210
Name: count, dtype: int64

 Item
Primary product, grain                         210
Price                                          210
Interest on operating capital                  210
Total, operating costs                         210
Total, gross value of production               210
Value of production less total costs listed    210
Hired labor                                    210
Total, allocated overhead                      210
Irrigated                                      210
Fertilizer                                     210
Value of production less operating costs       210
General farm overhead                          210
Taxes and insurance                            210
Enterprise size                                210
Custom services                                210
Seed                                           210
Chemicals                                      210
Fuel, lube, and electricity                    210
Repairs                                        210
Total, costs listed                            210
Yield                                          210
Capital recovery of machinery and equipment    210
Opportunity cost of land                       210
Opportunity cost of unpaid labor               210
Secondary product, silage                      210
Purchased irrigation water                     210
Dryland                                        205
Name: count, dtype: int64

 Units
dollars per planted acre         4620
percent of acres                  415
dollars per bushel at harvest     210
planted acres                     210
bushels per planted acre          210
Name: count, dtype: int64

 Size
No specific size    5665
Name: count, dtype: int64

 Region
Prairie Gateway          810
Southern Seaboard        810
Northern Great Plains    810
U.S. total               810
Northern Crescent        810
Heartland                810
Eastern Uplands          805
Name: count, dtype: int64

 Country
United States    5665
Name: count, dtype: int64

 Survey base year
Base survey of 2010    1134
Base survey of 2021     945
Base survey of 2005     945
Base survey of 2016     945
Base survey of 1996     940
Base survey of 2001     756
Name: count, dtype: int64
----------------------------


 Commodity
Cotton    5550
Name: count, dtype: int64

 Category
Operating costs              1850
Allocated overhead           1295
Supporting information        925
Gross value of production     555
Net value                     370
Production practices          370
Costs listed                  185
Name: count, dtype: int64

 Item
Value of production less operating costs       185
Value of production less total costs listed    185
Taxes and insurance                            185
Hired labor                                    185
Opportunity cost of unpaid labor               185
Price                                          185
Cottonseed price                               185
Dryland                                        185
Irrigated                                      185
Chemicals                                      185
Enterprise size                                185
Secondary product, cottonseed                  185
Cottonseed yield                               185
Fertilizer                                     185
Custom services                                185
Interest on operating inputs                   185
Yield                                          185
General farm overhead                          185
Total, gross value of production               185
Total, allocated overhead                      185
Repairs                                        185
Fuel, lube, and electricity                    185
Purchased irrigation water                     185
Total, costs listed                            185
Total, operating costs                         185
Capital recovery of machinery and equipment    185
Opportunity cost of land                       185
Ginning                                        185
Seed                                           185
Primary product, cotton lint                   185
Name: count, dtype: int64

 Units
dollars per planted acre    4255
dollars per pound            370
percent of acres             370
pounds per planted acre      370
planted acres                185
Name: count, dtype: int64

 Size
No specific size    5550
Name: count, dtype: int64

 Region
Prairie Gateway       870
Mississippi Portal    870
Fruitful Rim          870
Heartland             870
U.S. total            870
Southern Seaboard     870
Eastern Uplands       330
Name: count, dtype: int64

 Country
United States    5550
Name: count, dtype: int64

 Survey base year
Base survey of 2019    1470
Base survey of 2007    1440
Base survey of 1997    1080
Base survey of 2003     840
Base survey of 2015     720
Name: count, dtype: int64
----------------------------


 Commodity
Soybean    6026
Name: count, dtype: int64

 Category
Operating costs              2088
Allocated overhead           1624
Supporting information        696
Net value                     464
Gross value of production     464
Production practices          458
Costs listed                  232
Name: count, dtype: int64

 Item
Hired labor                                    232
Taxes and insurance                            232
Purchased irrigation water                     232
Enterprise size                                232
Fuel, lube, and electricity                    232
Fertilizer                                     232
Custom services                                232
Opportunity cost of land                       232
Total, operating costs                         232
Repairs                                        232
Seed                                           232
General farm overhead                          232
Capital recovery of machinery and equipment    232
Total, allocated overhead                      232
Value of production less total costs listed    232
Yield                                          232
Price                                          232
Value of production less operating costs       232
Interest on operating capital                  232
Total, costs listed                            232
Primary product, soybeans                      232
Chemicals                                      232
Total, gross value of production               232
Opportunity cost of unpaid labor               232
Irrigated                                      203
Dryland                                        203
Dryland                                         26
Irrigated                                       26
Name: count, dtype: int64

 Units
dollars per planted acre         4872
percent of acres                  458
planted acres                     232
bushels per planted acre          232
dollars per bushel at harvest     232
Name: count, dtype: int64

 Size
No specific size    6026
Name: count, dtype: int64

 Region
Prairie Gateway          754
Southern Seaboard        754
Eastern Uplands          754
Mississippi Portal       754
U.S. total               754
Northern Crescent        754
Heartland                754
Northern Great Plains    748
Name: count, dtype: int64

 Country
United States    6026
Name: count, dtype: int64

 Survey base year
Base survey of 2006    1248
Base survey of 2012    1248
Base survey of 1997    1040
Base survey of 2018    1040
Base survey of 2002     832
Base survey of 2023     618
Name: count, dtype: int64
----------------------------


 Commodity
Wheat    6204
Name: count, dtype: int64

 Category
Operating costs              1872
Allocated overhead           1456
Production practices         1004
Gross value of production     624
Supporting information        624
Net value                     416
Costs listed                  208
Name: count, dtype: int64

 Item
Total, operating costs                         208
General farm overhead                          208
Fertilizer                                     208
Seed                                           208
Other variable expenses                        208
Interest on operating inputs                   208
Total, gross value of production               208
Taxes and insurance                            208
Primary product, grain                         208
Secondary product, silage/straw/grazing        208
Value of production less operating costs       208
Total, costs listed                            208
Chemicals                                      208
Enterprise size                                208
Custom services                                208
Fuel, lube, and electricity                    208
Value of production less total costs listed    208
Yield                                          208
Opportunity cost of unpaid labor               208
Capital recovery of machinery and equipment    208
Hired labor                                    208
Repairs                                        208
Opportunity cost of land                       208
Total, allocated overhead                      208
Price                                          208
Spring wheat                                   180
Winter wheat                                   180
Durum wheat                                    180
Dryland                                        124
Irrigated                                      124
Dryland                                         72
Irrigated                                       72
Durum wheat                                     24
Winter wheat                                    24
Spring wheat                                    24
Name: count, dtype: int64

 Units
dollars per planted acre         4576
percent of acres                 1004
planted acres                     208
bushels per planted acre          208
dollars per bushel at harvest     208
Name: count, dtype: int64

 Size
No specific size    6204
Name: count, dtype: int64

 Region
Prairie Gateway          840
Basin and Range          840
U.S. total               840
Fruitful Rim             840
Heartland                832
Northern Great Plains    832
Northern Crescent        820
Southern Seaboard        180
Mississippi Portal       180
Name: count, dtype: int64

 Country
United States    6204
Name: count, dtype: int64

 Survey base year
Base survey of 2009    1680
Base survey of 1998    1620
Base survey of 2004    1050
Base survey of 2017    1050
Base survey of 2022     804
Name: count, dtype: int64
----------------------------


 Commodity
Corn        34
Soybeans    34
Wheat       34
Cotton      34
Rice        34
Peanuts     34
Sorghum     34
Oats        34
Barley      34
Name: count, dtype: int64

 Category
Operating costs       162
Allocated overhead    126
Costs listed           18
Name: count, dtype: int64

 Item
Seed                                           18
Fertilizer                                     18
Chemicals                                      18
Custom operations                              18
Fuel, lube, and electricity                    18
Repairs                                        18
Other variable expenses                        18
Interest on operating capital                  18
Total, operating costs                         18
Hired labor                                    18
Opportunity cost of unpaid labor               18
Capital recovery of machinery and equipment    18
Opportunity cost of land (rental rate)         18
Taxes and insurance                            18
General farm overhead                          18
Total, allocated costs                         18
Total, costs listed                            18
Name: count, dtype: int64

 Units
Dollars per planted acre    306
Name: count, dtype: int64

 Region
U.S. total    306
Name: count, dtype: int64

 Year
2026F    153
2027F    153
Name: count, dtype: int64
----------------------------

In [15]:
df_filtered = corn_df[corn_df['Units'].str.contains('planted acres', case=False, na=False)]
print(df_filtered)

     Commodity                Category             Item          Units  \
22        Corn  Supporting information  Enterprise size  planted acres
44        Corn  Supporting information  Enterprise size  planted acres
87        Corn  Supporting information  Enterprise size  planted acres
98        Corn  Supporting information  Enterprise size  planted acres
103       Corn  Supporting information  Enterprise size  planted acres
...        ...                     ...              ...            ...
3995      Corn  Supporting information  Enterprise size  planted acres
3996      Corn  Supporting information  Enterprise size  planted acres
3997      Corn  Supporting information  Enterprise size  planted acres
3998      Corn  Supporting information  Enterprise size  planted acres
3999      Corn  Supporting information  Enterprise size  planted acres

                  Size             Region        Country  Year  Value  \
22    No specific size          Heartland  United States  2025  274.0
44    No specific size    Prairie Gateway  United States  2025  499.0
87    No specific size         U.S. total  United States  2025  296.0
98    No specific size  Northern Crescent  United States  2025  184.0
103   No specific size  Southern Seaboard  United States  2025  255.0
...                ...                ...            ...   ...    ...
3995  No specific size  Southern Seaboard  United States  2020  163.0
3996  No specific size  Southern Seaboard  United States  2021  255.0
3997  No specific size  Southern Seaboard  United States  2022  255.0
3998  No specific size  Southern Seaboard  United States  2023  255.0
3999  No specific size  Southern Seaboard  United States  2024  255.0

         Survey base year
22    Base survey of 2021
44    Base survey of 2021
87    Base survey of 2021
98    Base survey of 2021
103   Base survey of 2021
...                   ...
3995  Base survey of 2016
3996  Base survey of 2021
3997  Base survey of 2021
3998  Base survey of 2021
3999  Base survey of 2021

[210 rows x 10 columns]

## Forecasting